name: Internal Link Checker

on:
  push:
    branches: [ main ]
    paths:
      - '**.html'
      - 'analysis/internal_link_checker.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.html'
      - 'analysis/internal_link_checker.py'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run internal link checker
        run: |
          python3 analysis/internal_link_checker.py

