name: Validators

on:
  push:
    branches: [ main, live/main ]
  pull_request:
    branches: [ main, live/main ]

jobs:
  validate:
    name: Run validators (HTML/MD links + reconciliation)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python
        run: python -V

      - name: Run internal link checker (HTML + Markdown)
        run: python analysis/internal_link_checker.py

      - name: Run reconciliation guard
        run: python analysis/reconciliation_guard.py

